### ISSUE TITLE
Small improvement

### ISSUE THREAD

**Issue by tomeralmog** [jsliang/eqHeight.coffee#12]
Hi,
Thank you for the plugin, I am building a responsive website, and needed the plugin to work only on desktop but not mobile.
I have modified the plugin to receive another option - breakpoint. if provided, the breakpoint will become min-width for the plugin to function.
I will create a pull request to show you the code if you wish.
Tomer

**Comment by jsliang** [comment]
Thank you Tomer! Really looking forward to the improvement :D

**Comment by tomeralmog** [comment]
Sorry, I can't seem to create a pull request

**Comment by tomeralmog** [comment]
Ok Done!
