### ISSUE TITLE
Impossible to scroll to bottom of page

### ISSUE THREAD

**Issue by PerBerntsen** [jsliang/eqHeight.coffee#18]
Hi, and thank you for a great script, that is also easy to implement for someone not familiar with javascript.

One small problem: All my pages contain some internal javascript that will cause column heights to change. So I've set

```
    option = {
    equalize_interval: 500,
    break_point: null
    };
```

   in the script itself. But when a page is scrolled to the bottom, it will jump back up 50 - 150px (seems to vary with page content) when the script executes. No content gets cut off, but it is quite annoying, and certainly confusing for the user.

A couple of examples here:
http://perberntsen.com/-index.php
http://perberntsen.com/Test/metsa1.php
(This is a work in progress, and most links in the menu are not functional)

I'd be very grateful if you could look into this.

**Comment by jsliang** [comment]
Hi @PerBerntsen ,

When the equalizing function executes, it follows these steps:
1. reset all the heights of column elements to each of their natural height value (in your page, that turns out to be `#accordion`: 449px, `#col1`: 3934px, `#col2`: 1491px)
2. get the maximum height value among the column elements (which would be 3934px)
3. reset all column elements to the maximum height value

It appears that some other scripts is changing the height of `#accordion` after eqHeight.
I inspected your page and found that the `#accordion` is always reset to height: 4096px after eqHeight sets all column elements to height: 3934px. As a result there are 162px (4096-3934) appended to the page, causing the jump up effects.
Could you identify which script is constantly changing the height of `#accordion`?

**Comment by PerBerntsen** [comment]
Hi Jenny,
Thanks for getting back to me.
I've made a test page with minimal content, and minimal javascript. I have removed all scripts (even Typekit) except jquery.dcjqaccordion.2.7.js and jquery.eqheight.js.

The accordion menu should be 220px +80px padding top and bottom - a total of 380px.It displays at a height of 542px - as you pointed out, that's 162px more. No height is declared - it is caused by

```
element.style {
height: 542px;
}
```

This has to(?) come from jquery.dcjqaccordion.2.7.js, but I can't see how - the only thing I did with this script was changing true to false in line 25.
And, the scrolling to bottom of page problem persists.

The test page is at http://perberntsen.com/test.php

**Comment by PerBerntsen** [comment]
I have removed the accordion script from the test page, so that jquery.eqheight.js is now the only script in the page. Still can't scroll to the bottom.
The menu is a server side include, so to make sure that wasn't the problem, I tried to remove the include code, and pasted the whole menu instead. No change.

Any ideas?
The test page is still at http://perberntsen.com/test.php

Thanks,
Per Berntsen

**Comment by PerBerntsen** [comment]
I finally figured it out. Removing the top and bottom padding from the ul #accordion solved the problem, it seems that the script has problems with vertical padding and border. The 162 pixels the page jumped up is exactly the 80px top and bottom padding, and the 1px top and bottom border.

As a workaround, I gave the first and last list item a top/bottom padding of 80px. The page still jumps up a few pixels (because the border is still there), but it's much better than it was. But it also introduces problems with hover on the top list item (not only the list item changes color, but also the padding area), and missing top border on the ul #accordion.

Would you be interested in looking into this?

Thanks,
Per Berntsen

**Comment by PerBerntsen** [comment]
Ok - I put the menu inside a div, and now it works properly. A little extra code, but problem solved!

**Comment by jsliang** [comment]
Hi @PerBerntsen , sorry for the late reply. (haven't been able to get on to github recently.) It's good to know the problem has been solved. :)

**Comment by xApep** [comment]
Yes, there is a problem with padding and borders. Is there any fix on that?
