### ISSUE TITLE
How does it work with a little known grid?

### ISSUE THREAD

**Issue by interlan** [jsliang/eqHeight.coffee#2]
I create some demo pages with a small uknown grid (https://github.com/carlopogus/Responsive-SASS-Grid) and I can not make equal height columns work.
As I am evaluating the new zurb foundation 4, it would nice if I could understand what is going on (but I am totally ignorant of javascript).
It would be nice If you could look into it.

Thanks,

Petros

**Comment by jsliang** [comment]
Yes it can work with this grid -- I modified the demo page of carlopogus's Responsive-SASS-Grid, and you can see the demo here: http://jsliang.com/Responsive-SASS-Grid/
This is the commit that applies eqHeight.coffee to the layout: jsliang/Responsive-SASS-Grid@9ab3f7eb6b50e819876beb5814422af9ab4e8764
Hope that helps :)

**Comment by interlan** [comment]
Miss Liang you are awesome.
It works like a charm!

Thank you,
Petros

**Comment by jsliang** [comment]
You're welcome. Glad that I can help!
