### ISSUE TITLE
Dynamic resizing within column fails due to static height

### ISSUE THREAD

**Issue by Visualq** [jsliang/eqHeight.coffee#4]
see http://jsfiddle.net/ufxbQ/10/

in order to fix this I attempted a min-height solution. This works, except for the box-sizing elements which require .outerHeight() instead of .height(); This will be in no way compatible with IE6. IE7 I'm not completely sure how jquery handle's .css('box-sizing').

The updated fiddle to min-height: http://jsfiddle.net/7wdjA/

It would be nice if after the animation the columns auto equalize but the .resize() event is only available on 'window'.

**Comment by jsliang** [comment]
Hi @Visualq, I found that if I change the jQuery import from "onload" to "no wrap - in &lt;body&gt;", then eqheight works: http://jsfiddle.net/ufxbQ/18/
I'm thinking that maybe there'll be an easier solution to this issue...

I might try more combination later. :D

**Comment by jsliang** [comment]
Close this issue for now. Please reopen it if this issue occurs again.
