### ISSUE TITLE
Documentation update for the newly added "equalize_interval" option

### ISSUE THREAD

**Issue by jsliang** [jsliang/eqHeight.coffee#5]
I've added a new `equalize_interval` option to the eqHeight function in v1.2.7.

By default, the equalizing function is called only on window resize.
If `equalize_interval` is specified with a number, for example, `500`, then the equalizing function is called every 500ms.

Will have to add this feature to README and the live demo page. Open an issue here to track it.

**Comment by andrewjlow** [comment]
Ah, just came across this and realised I need to set the equalize_interval. I've set it to null and it doesn't use any CPU anymore!

Thank you!

**Comment by jsliang** [comment]
Sorry that it took me so long to close this issue.

And thank you @andrewjlow for pointing out the bug I introduced in commits d26bc4aa6bf75916e3f21fa3900c8d2aab146e3f and f447c6742fe8f3b5831b96bf5e0b8a1da3b98ef8.
I fixed it in 9ed15f8e7e65717944413a808c51815c79ead461 and have add description of the `equalize_interval` option to README.
