### ISSUE TITLE
Column with dynamically changing content

### ISSUE THREAD

**Issue by restlessbee** [jsliang/eqHeight.coffee#6]
Hi there,

First, thanks hugely for this very helpful plugin.

I was looking to use it on a page where one of the columns with eqHeight applied toi it would have its content periodically changing via Flexslider 2 ( http://www.woothemes.com/flexslider/ ). It might start with 5 lines of text, then a new slide would come in and it would be 10 lines of text. Flexslider has a callback function that you can make fire after each slide transition completes: 

after: function(){},            //Callback: function(slider) - Fires after each slider animation completes 

I know flexslider isn't your thing, but do you think something like

<script type="text/javascript" charset="utf-8">
  $(window).load(function() {
    $('.flexslider').flexslider({
      animation: "slide",
      controlsContainer: ".flex-container",
      after: function(slider) {
        $(".row").eqHeight(".column");
      }
    });
  });
</script>

Would do the trick?

Thanks in advance for any advice you are able to provide!

Erik

**Comment by davidpaulsson** [comment]
You can trigger eqHeight again when your animation completes, something like this to make it run.

```
$('.your-selector').eqHeight();
$(window).resize();
```

**Comment by jsliang** [comment]
Hi, you can also try using the `equalize_interval` option to conduct repeatedly relayout, like this:

```
$(".row").eqHeight(".column", {equalize_interval: 500}); // relayout every 500ms
```

However, using this feature might incur huge performance overhead; see issues #5 and #7.
