### ISSUE TITLE
eqHeight causes 100% CPU in Firefox & Safari?

### ISSUE THREAD

**Issue by eobet** [jsliang/eqHeight.coffee#7]
When I load the demo page of eqHeight (http://jsliang.com/eqHeight.coffee/demo.html) and watch the Firefox process in my activity monitor the CPU consumption doubles and sometimes maxes out at 100%. In Safari, the processes also went from sub 10% to a constant 60-70% simply by having that demo page loaded.

Is this just my machine or is there something weird going on with eqHeight?

**Comment by davidpaulsson** [comment]
I'm experiencing the same thing. It is worrying when eqHeight is the best solution I found so far with the same height problem for a responsive interface.

**Comment by andrewjlow** [comment]
Yes, I've noticed it too. From the looks of the javascript code, it uses an equalize_interval = 500  to continuously check and equalize the heights?

**Comment by andrewjlow** [comment]
OK, read the other issues and it is the equalize_interval. I've set it to null in the javascript and my CPU goes back to normal.

**Comment by jsliang** [comment]
Thank you @eobet & @davidpaulsson, for reporting this problem; and @andrewjlow for pointing out the root cause. This issue shall have been fixed by 9ed15f8e7e65717944413a808c51815c79ead461.
