### ISSUE TITLE
bootstrap 3 thumbnails

### ISSUE THREAD

**Issue by twiddly** [jsliang/eqHeight.coffee#9]
doesn't seem to work for bootstrap 3 thumbnails component

I tried
 $(".row").eqHeight(".thumbnail");
and
 $(".row").eqHeight();

**Comment by jsliang** [comment]
Hi twiddly,
`$(".row").eqHeight(".thumbnail");` seems to work for me. Is this what you're expecting? http://jsfiddle.net/tpPEK/ (need to enlarge the "Result" pane at bottom right)
jsliang

**Comment by LingoSam** [comment]
I have also tested the exact issue above, and found no problem. I think the issue may lie elsewhere.
